### PR TITLE
update CSS to bootstrap 3 style

### PR DESCRIPTION
**Pull request by razvanphp**
composer installed `bower-asset/typeahead.js: v0.11.1` where some classes changed:

- `.tt-dropdown-menu` is now called `.tt-menu`
- `.tt-is-under-cursor` is now called `.tt-cursor`
- `.tt-query` is now called `.tt-input`

reference: https://stackoverflow.com/questions/20198247/twitters-typeahead-js-suggestions-are-not-styled-have-no-border-transparent-b

also, for bootstrap 3 styling the colors and borders changed, most of the values you can check here:
https://github.com/twbs/bootstrap/blob/v3.3.6/less/variables.less

would love to see this merged, thank you for your work!

### CODE REVIEW

**Comment by razvanphp** [comment]
ping @dzona @tonydspaniard

**Comment by tonydspaniard** [comment]
Hi @razvanphp will check during the week... thanks

**Comment by razvanphp** [comment]
Hi @tonydspaniard, it works great on dev-master, please tag & release version 3.0. Thanks!

**Comment by tonydspaniard** [comment]
@razvanphp great... and done... version `3.0.0` has been pushed.

**Comment by tonydspaniard** [comment]
@razvanphp what do you think about: https://github.com/bassjobsen/typeahead.js-bootstrap4-css 

I think is about time :(

**Comment by razvanphp** [comment]
@tonydspaniard do you mean we should remove the CSS from this repo and link to those? It seems there are different ones for BS3 and BS4. I'll try them and see how they look.

**Comment by tonydspaniard** [comment]
@razvanphp no, I think I should create a version for BS4

**Pull request merged**
