### PR TITLE
Implement client events

### LINKED ISSUE #6: Events
hi, i use widget and  i have a question about events. how  i can  specify the  events (https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events) in your widget?

### PR DESCRIPTION
**Pull request by razvanphp**
This PR fixes #6 

Implementation similar to [jui Widget.php](https://github.com/yiisoft/yii2-jui/blob/master/Widget.php#L48)

tests passing, already tested in my project.

### CODE REVIEW

**Comment by razvanphp** [comment]
Please also bump minor version and add tag when merging. Thank you!

**Comment by creocoder** [comment]
@razvanphp Good work! Thanks!

**Comment by razvanphp** [comment]
@creocoder welcome! please do not forget about the tag.

**Comment by creocoder** [comment]
@radzserg Thanks for remind, but it already tagged as new release, including raise to new typeahead js version ;-)

**Pull request merged**
